language: python

dist: trusty
sudo: required

python:
  - 3.5
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

services:
  - mysql
  - postgresql

env:
  global:
    - secure: mU1dWo3E44OJvf0cyvGNiC84dYTieWKrAy33Osec2QqABOF3PCzeSQs981zVY37FdaM5WDOKeJXbF9ipBC0im0Gt9DAm0Se/MnijroNJkniH0MOq6Di6W14CzJL7FLYba+DkEiFb/zSCoZQKDW08akqg+26Ok2696tIaLUQQQVLQQmB76FkTLZpnmq0DY/GddF9neLIgamQWPIrW/aWRzIT1TkhACT/y4jULcuvcze16VkDCWjqLVjOM0QgXEOF4D5pOSo2+qEsPF0UGAEPDnwBv0OwEl/PoMNIQiE8BaTkC0nGjHmKWWGJ60vHEb0KHkKO+3cnvJtXwy+4PWNZbEI9xgRy1cgRi4f5ePQjzfrTc4mrKKzYzhs32FcFEdC0OInEvJQm69xQooI/htwTaf2cxeOesvOwf/DWh3V88/5E8W9FE5DcVOXGXI/9bdjIiX9roOWr/nWDCT5AGGQ+6J+2wJrvvabVzJz8u4ezbwsMUq/z8sUkrxUwzTscxF6WJEr7fstkKiWcZ15zfqpSN1r/pm6DMWIGzkvgFVPygZPIRfXA0ud5ZgyaXestIBc0lDYMmQPbpXRWD0SaxsLHb863LFPjscA2UwvMdMpZYNYVZOOhF6HT9Y3RY8LDAq7/Mgj3ZtWU7bze//DlhkrFFPfKtKbv22iAZbdPDu0b4ksk=
  matrix:
    # Unit tests.
    - TOXENV=py35-unit-mysql
    - TOXENV=py35-unit-postgresql
    - TOXENV=py36-unit-mysql
    - TOXENV=py36-unit-postgresql
    - TOXENV=py35-integration-mysql
    - TOXENV=py36-integration-mysql

matrix:
#  include:
#    - os: linux
#    - os: osx
  exclude:
    - python: 3.6
      env: TOXENV=py35-unit-mysql
    - python: 3.6
      env: TOXENV=py35-unit-postgresql
    - python: 3.6
      env: TOXENV=py35-integration-mysql
    - python: 3.6
      env: TOXENV=py35-integration-postgresql
    - python: 3.5
      env: TOXENV=py36-unit-mysql
    - python: 3.5
      env: TOXENV=py36-unit-postgresql
    - python: 3.5
      env: TOXENV=py36-integration-mysql
    - python: 3.5
      env: TOXENV=py36-integration-postgresql

  last_finish: true

before_install:
  - sleep 15
  - mysql -u root -e "CREATE DATABASE pyplanet CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  - psql -c "create database pyplanet ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';" -U postgres
  - psql -c "CREATE USER pyplanet WITH PASSWORD 'pyplanet';" -U postgres

install:
  - pip install tox codacy-coverage python-coveralls -U pip
  - tests/_scripts/travis_dedicated_setup.sh

before_script:
  - tests/_scripts/travis_config.sh
  - tests/_scripts/travis_dedicated_start.sh

script:
  - tox -e $TOXENV -- --with-coverage --cover-package=pyplanet --cover-xml --cover-xml-file=coverage.xml
  - tests/_scripts/travis_build_binary.sh

after_success:
  - coveralls --ignore-errors
#  - tests/_scripts/travis_coverage.sh
#  - python-codacy-coverage -r coverage.xml

after_failure:
  - cat dedicated/Logs/*

deploy:
  provider: releases
  api_key:
    secure: jmdxPQpZOZrOgGLkls1IznIuYs43CEU+Q5GyQDGcIfOQtttOxiwgKjsCg37/1RVHylpSIqRYWVrzSlcw5k4bA9SANWjG4ENtdrG8J63LvjzAHUfzAquxwmHXpv1j+dU5heOheIgl5ckmXvWvMosddu412sEBtDtwuIwtV2v3VnYy8OV21mKg/JmCjJTZt/MurBfqgNyoMpKljIBiAuknlpKX8+Px4oxOZVR98GkmbEm5I9SxhrArr8XX8yshAyWyHPHF2ubiFUajkpl9yLrapiZwtNMJMEsvNcRFN3wL8anNJwmXVUWCRV/MXBYJpMoa31DR9YmlTYTS/QhxHhdl71y/PB2UMHcGlr+0ms5/fgiSeaBls2EIjyqd80+YIsP/lHGrjYv7BaZZEquXUHdvd51zkYfOv6YmmaZKq62pxKRAX1jyhQdwfbkkJPeqy7YjNrVT9gikbupLQecenFQ3tttbb6TOtsdDPeiDcYWW1wqpE+DoGVkludwN6YTEGkm7G+YX44PFk8aOEZJN31hibqwOXHIDUK/oiaGOMv4faftykE9Yx0YM9wJ1IjWrqw5A3Vp+A82yJ2jFHf+WK7bMAxoj0T23nIHNPuM74Bmv2KWBXWmXH/VFuMvjSeJHYzMWbUoIRe70ClSZsc8iikQkp1iZoeYaOlw3HWq21wUrh6I=
  file: dist/pyplanet
  on:
    repo: PyPlanet/PyPlanet
    tags: true
  draft: true
